# Generated by Django 3.2.4 on 2021-07-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pin_code',
            field=models.CharField(default='', max_length=30, verbose_name='ПИН-Код паспорта'),
        ),
        migrations.AddField(
            model_name='patient',
            name='reasonOfVisit',
            field=models.TextField(blank=True, verbose_name='Причина визита в больницу'),
        ),
    ]
