# Generated by Django 3.2.4 on 2021-07-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210702_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='count_of_workers',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, verbose_name='Количество работников(макс 100): '),
        ),
    ]
