# Generated by Django 3.2.4 on 2021-07-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospital_count_of_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='head_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.headdoctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nurse',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.nurse'),
        ),
        migrations.AlterField(
            model_name='headdoctor',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital', verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='count_of_workers',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Количество работников(макс 100): '),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='head_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.headdoctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.nurse'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reasonOfVisit',
            field=models.TextField(verbose_name='Причина визита в больницу'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Ф.И.О пациента'),
        ),
    ]
